# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84acf8283b774b21e1664c73e27dc5fbb9b9bd75bd2e16d1f558ff09bdd90bd7d660968c85b617fbd6dc4ccb0b4ef0dd7854f3fcc8929d4ff04681a2c6e77f7c

test:
  secret_key_base: f2e5dfc2acd09931f7804eed5e0a16b8d9ead797b78eb42e1daf66a78728d49310ea3ddc5b0e6401edc166adeeece263318af0b50180760102dac4ca74e5d3d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
